export const STORAGE_KEYS = {
    APP_SETTINGS: 'app_settings',
    AVATAR_CACHE: 'cache',
    AVATAR_OWN: 'own',
    AUTH_ORIGINAL_USERNAME: 'original_username',
    AUTH_USERNAME: 'username',
    AVATAR_PUBLICATION_STATE: 'avatar_publication_state',
    BLOCK_LIST_GLOBAL: 'blocklist:__global__',
    CALL_HISTORY: 'call_history',
    CONVERSATIONS_METADATA: 'conversations_metadata',
    DELIBERATE_CALL_ADMISSION: 'deliberate-call-admission',
    DELIVERY_ACKS: 'pending-acks',
    DELIVERY_RECEIPT_OUTBOX: 'outbox',
    EXPLICIT_LOGOUT: 'qorc_explicit_logout',
    PROFILE_AVATARS: 'profile_avatars',
    KEY_TRANSPARENCY_CHECKPOINT: 'checkpoint',
    KEY_TRANSPARENCY_OWN_TRANSITION: 'own-transition',
    LINK_PREVIEW_INDEX: '__index__',
    PENDING_RETRY_ALL: 'all',
    SERVER_PQ_PIN: 'server_pq_pin',
    THEME: 'theme',
    TOR_BRIDGES_ENABLED: 'qorc_tor_bridges_enabled',
    TOR_BRIDGE_LINES: 'qorc_tor_bridge_lines',
    TOR_BRIDGE_TRANSPORT: 'qorc_tor_bridge_transport',
    USAGE_STATS: 'usage_stats',
    USERS: 'users',
    SINGLETON: '__singleton__',
} as const;

export const STORAGE_PREFIXES = {
    DISCOVERY_MATERIAL: 'discmat:',
    EPHEMERAL: 'ephemeral:',
    INSTANCE: 'qorc',
    KEY_TRANSPARENCY_AUTHORIZATION: 'kt-authorizations:',
    KEY_TRANSPARENCY_CONTACT: 'kt-contact:',
    KEY_TRANSPARENCY_HEAD: 'kt-head:',
    KEY_TRANSPARENCY_INCIDENT: 'kt-incident:',
    KEY_TRANSPARENCY_MONITOR: 'kt-monitors:',
    KEY_TRANSPARENCY_RECORD: 'kt-records:',
    KEY_TRANSPARENCY_WARNING: 'kt-warnings:',
    LAST_AUTH_DISPLAY: 'last-auth-display:',
    LAST_AUTH_USER: 'last-auth-user:',
    PEER_CERTIFICATE: 'peercert:',
    PRIVACY_PASS_TOKEN: 'pp_tokens_',
    PRIVATE_AUTH_SLOT: 'private_auth_slot_',
    REGISTRATION_ATTEMPT: 'registration_attempt_',
    SPOOL_CONSUMED_PROBES: 'spoolconsumed:',
    SPOOL_DETECTION: 'spooldet:',
    SPOOL_PEER_DETECTION: 'spoolpeerdet:',
} as const;

export const STORAGE_KEY_DOMAINS = {
    DISCOVERY_MATERIAL: 'qorc-discovery-material-cache',
    DATABASE_OWNER: 'qorc-db-owner',
    GATEKEEPER_TOKEN_STORE: 'qorc-gatekeeper-token-store',
    KEY_TRANSPARENCY_AUTHORIZATION: 'qorc-key-transparency-authorization-storage',
    KEY_TRANSPARENCY_CONTACT: 'qorc-kt-contact-storage',
    KEY_TRANSPARENCY_HEAD: 'qorc-kt-head-storage',
    KEY_TRANSPARENCY_INCIDENT: 'qorc-kt-incident-storage',
    KEY_TRANSPARENCY_MONITOR: 'qorc-key-transparency-monitor-storage',
    KEY_TRANSPARENCY_RECORD: 'qorc-key-transparency-record-storage',
    KEY_TRANSPARENCY_WARNING: 'qorc-key-transparency-warning-storage',
    LOCAL_ACCOUNT_SCOPE: 'qorc-local-account-scope',
    LOCAL_SERVER_SCOPE: 'qorc-local-server-scope',
    LINK_PREVIEW_CACHE: 'qorc-link-preview-cache',
    PEER_CERTIFICATE: 'qorc-peer-certificate-cache',
    PRIVATE_AUTH_SLOT: 'qorc-private-auth-slot',
    SPOOL_CONSUMED_PROBES: 'qorc-spool-consumed-probes',
    SPOOL_DETECTION: 'qorc-spool-detection-key',
    SPOOL_PEER_DETECTION: 'qorc-spool-peer-detection',
} as const;

export const STORAGE_STORES = {
    AUTH_METADATA: 'auth_metadata',
    BLOCK_LIST: 'blockListData',
    DATA: 'data',
    DELIVERY_RECEIPTS: 'delivery-receipts',
    EMOJI_DATA: 'emoji_data',
    ENCRYPTED_STORAGE: 'encrypted_storage',
    FILES: 'files',
    LINK_PREVIEWS: 'link-previews',
    MESSAGE_CONVERSATIONS: 'msgconv',
    PENDING_RETRY: 'pending-retry',
    TRANSPORT_DELIVERY: 'transport-delivery',
} as const;
