export const STORAGE_KEYS = {
    APP_SETTINGS: 'app_settings_v1',
    AVATAR_CACHE: 'cache',
    AVATAR_OWN: 'own',
    AUTH_ORIGINAL_USERNAME: 'original_username',
    AUTH_USERNAME: 'username',
    AVATAR_PUBLICATION_STATE: 'avatar_publication_state_v1',
    BLOCK_LIST_GLOBAL: 'blocklist:__global__',
    CALL_HISTORY: 'call_history_v1',
    CONVERSATIONS_METADATA: 'conversations_metadata',
    DELIBERATE_CALL_ADMISSION: 'deliberate-call-admission-v2',
    DELIVERY_ACKS: 'pending-acks',
    DELIVERY_RECEIPT_OUTBOX: 'outbox',
    EXPLICIT_LOGOUT: 'qor_explicit_logout_v1',
    PREFERRED_CAMERA: 'preferred_camera_device_id_v2',
    PROFILE_AVATARS: 'profile_avatars',
    KEY_TRANSPARENCY_CHECKPOINT: 'checkpoint',
    KEY_TRANSPARENCY_OWN_TRANSITION: 'own-transition',
    PENDING_RETRY_ALL: 'all',
    SERVER_PQ_PIN: 'server_pq_pin_v4',
    THEME: 'theme',
    TOR_AUTO_CONNECT: 'qor_tor_auto_connect_v1',
    TOR_AUTO_START: 'qor_tor_auto_start_v1',
    TOR_BRIDGES_ENABLED: 'qor_tor_bridges_enabled_v1',
    TOR_BRIDGE_LINES: 'qor_tor_bridge_lines_v1',
    TOR_BRIDGE_TRANSPORT: 'qor_tor_bridge_transport_v1',
    USAGE_STATS: 'usage_stats',
    USERS: 'users',
    SINGLETON: '__singleton__',
} as const;

export const STORAGE_PREFIXES = {
    DISCOVERY_MATERIAL: 'discmat:v1:',
    EPHEMERAL: 'ephemeral:',
    INSTANCE: 'qor:v1',
    KEY_TRANSPARENCY_AUTHORIZATION: 'kt-authorizations:',
    KEY_TRANSPARENCY_CONTACT: 'kt-contact:',
    KEY_TRANSPARENCY_HEAD: 'kt-head:',
    KEY_TRANSPARENCY_INCIDENT: 'kt-incident:',
    KEY_TRANSPARENCY_MONITOR: 'kt-monitors:',
    KEY_TRANSPARENCY_RECORD: 'kt-records:',
    KEY_TRANSPARENCY_WARNING: 'kt-warnings:',
    LAST_AUTH_DISPLAY: 'last-auth-display:',
    LAST_AUTH_USER: 'last-auth-user:',
    PEER_CERTIFICATE: 'peercert:v6:',
    PRIVACY_PASS_TOKEN: 'pp_tokens_',
    PRIVATE_AUTH_SLOT: 'private_auth_slot_',
    REGISTRATION_ATTEMPT: 'registration_attempt_v1_',
    SPOOL_CONSUMED_PROBES: 'spoolconsumed:v1:',
    SPOOL_DETECTION: 'spooldet:v1:',
    SPOOL_PEER_DETECTION: 'spoolpeerdet:v1:',
} as const;

export const STORAGE_KEY_DOMAINS = {
    DISCOVERY_MATERIAL: 'qor-discovery-material-cache-v1',
    DATABASE_OWNER: 'qor-db-owner-v2',
    GATEKEEPER_TOKEN_STORE: 'qor-gatekeeper-token-store-v2',
    KEY_TRANSPARENCY_AUTHORIZATION: 'qor-key-transparency-authorization-storage-v1',
    KEY_TRANSPARENCY_CONTACT: 'qor-kt-contact-storage-v1',
    KEY_TRANSPARENCY_HEAD: 'qor-kt-head-storage-v1',
    KEY_TRANSPARENCY_INCIDENT: 'qor-kt-incident-storage-v1',
    KEY_TRANSPARENCY_MONITOR: 'qor-key-transparency-monitor-storage-v2',
    KEY_TRANSPARENCY_RECORD: 'qor-key-transparency-record-storage-v2',
    KEY_TRANSPARENCY_WARNING: 'qor-key-transparency-warning-storage-v1',
    LOCAL_ACCOUNT_SCOPE: 'qor-local-account-scope-v1',
    LOCAL_SERVER_SCOPE: 'qor-local-server-scope-v1',
    PEER_CERTIFICATE: 'qor-peer-certificate-cache-v6',
    PRIVATE_AUTH_SLOT: 'qor-private-auth-slot-v4',
    SPOOL_CONSUMED_PROBES: 'qor-spool-consumed-probes-v1',
    SPOOL_DETECTION: 'qor-spool-detection-key-v1',
    SPOOL_PEER_DETECTION: 'qor-spool-peer-detection-v1',
} as const;

export const STORAGE_STORES = {
    AUTH_METADATA: 'auth_metadata',
    BLOCK_LIST: 'blockListData',
    DATA: 'data',
    DELIVERY_RECEIPTS: 'delivery-receipts',
    EMOJI_DATA: 'emoji_data',
    ENCRYPTED_STORAGE: 'encrypted_storage',
    FILES: 'files',
    MESSAGE_CONVERSATIONS: 'msgconv',
    PENDING_RETRY: 'pending-retry',
    TRANSPORT_DELIVERY: 'transport-delivery',
} as const;
