import {
  KEY_TRANSPARENCY_PROTOCOL,
  OPAQUE_AUTH_SIGNATURE_CONTEXT,
  SPOOL_TAG_PROTOCOL,
} from '../../../shared/protocol-keys.js';

export const PROTOCOL_KEYS = Object.freeze({
  ACCOUNT_AUTH_KDF: 'qorc-Account-Auth-Argon2id\0',
  ACCOUNT_AUTH_SECRET: 'qorc-account-auth-secret\0',
  ACCOUNT_ROOT_PAYLOAD: 'qorc-account-root-payload',
  ACCOUNT_ROOT_CERTIFICATE_SIGNING: 'account-root-certificate',
  AVATAR_BLOB_AAD: 'qorc-avatar-purb',
  AVATAR_GET_HTTP_POW: 'qorc-avatar-get-http-pow',
  AVATAR_PUT_HTTP_POW: 'qorc-avatar-put-http-pow',
  CERTIFIED_PEER_BUNDLE: 'qorc-certified-peer-bundle',
  DEVICE_CERTIFICATE: 'qorc-device-certificate',
  DEVICE_CERTIFICATE_PAYLOAD: 'qorc-device-certificate-payload',
  DEVICE_CERTIFICATE_SIGNING: 'device-certificate',
  DEVICE_ENVELOPE_SIGNING: 'device-envelope',
  DEVICE_ID: 'qorc-device-id',
  DEVICE_SUBKEY_BINDING: 'qorc-device-subkey-binding',
  DEVICE_SUBKEY_BINDING_PAYLOAD: 'qorc-device-subkey-binding-payload',
  EXPECTED_SERVER_HEADER: 'x-qorc-expected-server-url',
  DISCOVERY_BLOB_AAD: 'qorc-discovery-blob-purb',
  DISCOVERY_BLOB_SELECTOR: 'qorc-discovery-blob-selector',
  DISCOVERY_COVER_PUBLICATION: 'qorc-discovery-cover-publication',
  DISCOVERY_QUERY_DECOY: 'qorc-discovery-query-decoy',
  DISCOVERY_BUCKET_HTTP_POW: 'qorc-discovery-bucket-http-pow',
  DISCOVERY_BUCKET_ID: 'qorc-discovery-bucket',
  DISCOVERY_BUCKET_KEY: 'qorc-discovery-bucket-key',
  DISCOVERY_BUCKET_MANIFEST: 'qorc-discovery-bucket-manifest',
  DISCOVERY_ENCRYPTION: 'discovery-encryption-key',
  DISCOVERY_MATERIAL_STORE: 'qorc-discovery-material-store',
  DISCOVERY_OPRF_POW: 'qorc-discovery-oprf-pow',
  DISCOVERY_PUBLISH_POW: 'qorc-discovery-publish-pow',
  DISCOVERY_TOKEN: 'discovery-token',
  FILE_TRANSFER_MAC_SALT: 'ft-mac-salt',
  GATEKEEPER_KDF: 'qorc-Server-Entry-Argon2id',
  HYBRID_ENVELOPE_PROTOCOL: 'hybrid-envelope',
  HYBRID_INNER_KDF_PREFIX: 'qorc-hybrid:inner:',
  HYBRID_KEY_KDF: 'qorc hybrid key',
  HYBRID_OUTER_KDF_PREFIX: 'qorc-hybrid:outer:',
  IDENTITY_ROOT: 'qorc-identity-root',
  INNER_ENVELOPE_PROTOCOL: 'inner-envelope',
  INCOMING_FILE_MESSAGE_ID: 'qorc-incoming-file-message-id',
  INBOUND_VAULT: 'qorc-inbound-vault',
  KEY_TRANSPARENCY_AUTHORIZATION_STORE: 'qorc-key-transparency-authorization-store',
  KEY_TRANSPARENCY_CHECKPOINT: 'qorc-key-transparency-checkpoint',
  KEY_TRANSPARENCY_CLIENT_STATE: 'qorc-key-transparency-client-state',
  KEY_TRANSPARENCY_CONTACT: 'qorc-key-transparency-contact',
  KEY_TRANSPARENCY_EPOCH_LABEL: 'qorc-Key-Transparency-Epoch-Label\0',
  KEY_TRANSPARENCY_KEY_COMMITMENT: 'qorc-Key-Transparency-Key-Commitment\0',
  KEY_TRANSPARENCY_LABEL: 'qorc-Key-Transparency-Label\0',
  KEY_TRANSPARENCY_MONITOR_STORE: 'qorc-key-transparency-monitor-store',
  KEY_TRANSPARENCY_PROTOCOL,
  KEY_TRANSPARENCY_RECORD_STORE: 'qorc-key-transparency-record-store',
  KEY_TRANSPARENCY_RECOVERY_SIGNING: 'key-transparency-recovery',
  KEY_TRANSPARENCY_SIGNER_KEY: 'qorc-Key-Transparency-Signer-Key\0',
  KEY_TRANSPARENCY_SIGNING: 'key-transparency',
  KEY_TRANSPARENCY_WARNING_STORE: 'qorc-key-transparency-warning-store',
  NATIVE_PENDING_DECRYPT: '__native-pending-decrypt',
  NOISE_KEY_CONFIRMATION: 'qorc-p2p-key-confirm',
  NOISE_CALL_STREAM_KEY_CONTEXT_PREFIX: 'qorc-call-stream-key:',
  NOISE_CALL_STREAM_KEY_SALT: 'qorc-call-stream-key-salt',
  NOISE_CONFIRMATION_SEPARATOR: ':confirm:',
  NOISE_COMPLETE_TRANSCRIPT_SUFFIX: ':complete-transcript',
  NOISE_PROTOCOL: 'hybrid-mlkem1024-mldsa87-session',
  NOISE_SESSION_SALT: 'qorc-hybrid-mlkem1024-mldsa87-session',
  OPAQUE_AUTH_SIGNATURE_CONTEXT,
  OPAQUE_ENVELOPE_KEY: 'OPAQUE-Envelope-Key',
  OPAQUE_EXPORT_KEY: 'OPAQUE-Export-Key',
  OPAQUE_OPRF_INPUT: 'OPAQUE-OPRF-Input',
  P2P_CHANNEL: 'qorc-p2p-channel',
  P2P_LOCAL_KEY_SELF_TEST: 'qorc-p2p-local-key-self-test',
  P2P_TRANSCRIPT_SIGNING: 'p2p-transcript',
  PEER_CERTIFICATE_ATTESTATION: 'qorc-peer-certificate',
  PEER_CERTIFICATE_IDENTITY: 'qorc-peer-certificate-identity',
  PEER_CERTIFICATE_PAYLOAD: 'qorc-peer-certificate-payload',
  PEER_CERTIFICATE_STORE: 'qorc-peer-certificate-store',
  PQ_ANONYMOUS_HTTP_ADMISSION_POW: 'qorc-PQ-Anonymous-HTTP-Admission-PoW\0',
  PQ_ANONYMOUS_HTTP_PROTOCOL: 'qorc-pq-anonymous-http',
  PQ_ANONYMOUS_HTTP_REQUEST_AAD: 'qorc-PQ-Anonymous-HTTP-Request\0',
  PQ_ANONYMOUS_HTTP_REQUEST_KDF: 'qorc-pq-anonymous-http-request',
  PQ_ANONYMOUS_HTTP_REQUEST_MAGIC: 'QORCAHRQ',
  PQ_ANONYMOUS_HTTP_RESPONSE_AAD: 'qorc-PQ-Anonymous-HTTP-Response\0',
  PQ_ANONYMOUS_HTTP_RESPONSE_KDF: 'qorc-pq-anonymous-http-response',
  PQ_ANONYMOUS_HTTP_RESPONSE_MAGIC: 'QORCAHRS',
  PQ_ANONYMOUS_HTTP_RESPONSE_SIGNATURE: 'qorc-PQ-Anonymous-HTTP-Response-Signature\0',
  PRIVACY_PASS_NULLIFIER: 'PrivacyPass-Nullifier',
  PRIVACY_PASS_OPRF_INPUT: 'PrivacyPass-OPRF-Input',
  PRIVACY_PASS_REDEMPTION_MAC: 'PrivacyPass-Redemption-MAC',
  PRIVATE_AUTH_REQUEST: 'qorc-private-auth-request\0',
  ROUTE_PROOF_KIND: 'route-proof',
  SESSION_KEY_KDF_PREFIX: 'session-key:',
  SECURE_DB_AEAD: 'securedb-aead',
  SECURE_DB_FILE_AAD: 'securedb-file-aead',
  SEALED_ENVELOPE_CACHE: 'qorc-sealed-envelope-cache\0',
  SEALED_ENVELOPE_PROTOCOL: 'sealed-sender',
  SEALED_SENDER_AAD: 'qorc-sealed-sender:aes-256-gcm:ml-kem-1024',
  SEALED_SENDER_KDF: 'qorc-sealed-sender:key',
  SIGNAL_PREKEY_BUNDLE: 'qorc-signal-prekey-bundle',
  SIGNAL_DEDUP: 'qorc-signal-dedup',
  SPOOL_CONSUMED_PROBE_STORE: 'qorc-spool-consumed-probe-store',
  SPOOL_TAG_PROTOCOL,
  UNIFIED_CRYPTO_MAC: 'quantum-secure-mac',
  WS_PQ_CELL_AAD: 'qorc-WS-PQ-Cell-AAD\0',
  WS_PQ_BASE_SALT_SUFFIX: ':two-way-ephemeral-base',
  WS_PQ_CLIENT_RECV: 'ws-pq-client-recv',
  WS_PQ_CLIENT_RECV_SALT_SUFFIX: ':client-recv',
  WS_PQ_CLIENT_SEND: 'ws-pq-client-send',
  WS_PQ_CLIENT_SEND_SALT_SUFFIX: ':client-send',
  WS_PQ_FINAL_SALT_SUFFIX: ':two-way-ephemeral-final',
  WS_PQ_HANDSHAKE_ACK: 'qorc-WS-PQ-Handshake-Ack',
  WS_PQ_HANDSHAKE_REQUEST: 'qorc-WS-PQ-Handshake-Request',
  WS_PQ_PROTOCOL: 'pq-ws',
  WS_PQ_TWO_WAY_EPHEMERAL_BASE: 'ws-pq-two-way-ephemeral-base',
} as const);
